=== linzhp/jEdit-Clone/modes/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION
	| MARKUP | OPERATOR | DIGIT | INVALID" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-type 'TYPE ( %tokens; ) "NULL"' >
<!ENTITY % att-at-line-start 'AT_LINE_START ( "TRUE" | "FALSE" ) "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH ( "TRUE" | "FALSE" ) "FALSE"' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS, RULES* ) >

<!-- MODE attributes -->
<!ATTLIST MODE
	name ( #PCDATA ) #REQUIRED >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME #PCDATA #REQUIRED
	VALUE #PCDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( TERMINATE | WHITESPACE | SPAN | EOL_SPAN | MARK_PREVIOUS |
	MARK_FOLLOWING | SEQ )+ KEYWORDS? >

<!-- RULES attributes -->
<!ATTLIST RULES
	IGNORE_CASE ( "TRUE" | "FALSE" ) "FALSE"
	HIGHLIGHT_DIGITS ( "TRUE" | "FALSE" ) "FALSE"
	SET #PCDATA
	ESCAPE #PCDATA
	DEFAULT ( %tokens; ) "NULL" >

<!-- RULES children -->
<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >

<!-- TERMINATE attributes -->
<!ATTLIST TERMINATE AT_CHAR ( #PCDATA ) #REQUIRED >

<!-- WHITESPACE element -->
<!ELEMENT WHITESPACE ( #PCDATA ) >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-at-line-start;
	%att-exclude-match;
	NO_LINE_BREAK ( "TRUE" | "FALSE" ) "FALSE"
	NO_WORD_BREAK ( "TRUE" | "FALSE" ) "FALSE"
	DELEGATE #PCDATA >

<!-- SPAN children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ELEMENT END ( #PCDATA ) >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-at-line-start;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-at-line-start;
	%att-exclude-match; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-at-line-start;
	%att-exclude-match; >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-at-line-start; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS ( NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION | MARKUP
	| OPERATOR | DIGIT | INVALID )+ >

<!-- KEYWORDS attributes -->
<!ATTLIST KEYWORDS
	IGNORE_CASE ( "TRUE" | "FALSE" ) "FALSE" >

<!-- KEYWORDS children -->
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== linzhp/jEdit-Clone/modes/vhdl.xml
<?xml version="1.0"?>

<!-- VHDL mode, contributed by Dante Fabrizio -->

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE NAME="vhdl">
	<PROPS>
		<PROPERTY NAME="label" VALUE="VHDL" />
		<PROPERTY NAME="filenameGlob" VALUE="*.vhd" />
		<PROPERTY NAME="blockComment" VALUE="--" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
	</PROPS>
	<RULES ESCAPE="\">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<EOL_SPAN TYPE="COMMENT1">--</EOL_SPAN>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">/=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">:</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>

		<SEQ TYPE="OPERATOR">**</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="NULL">}</SEQ>
		<SEQ TYPE="NULL">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE"
			AT_LINE_START="TRUE">:</MARK_PREVIOUS>
		<SEQ TYPE="NULL">:</SEQ>

		<KEYWORDS IGNORE_CASE="TRUE">
			<KEYWORD1>architecture</KEYWORD1>
			<KEYWORD1>alias</KEYWORD1>
 			<KEYWORD1>assert</KEYWORD1>
			<KEYWORD1>entity</KEYWORD1>
			<KEYWORD1>process</KEYWORD1>
			<KEYWORD1>variable</KEYWORD1>
			<KEYWORD1>signal</KEYWORD1>
			<KEYWORD1>function</KEYWORD1>
			<KEYWORD1>generic</KEYWORD1>
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>out</KEYWORD1>
			<KEYWORD1>inout</KEYWORD1>
			<KEYWORD1>begin</KEYWORD1>
			<KEYWORD1>end</KEYWORD1>
			<KEYWORD1>component</KEYWORD1>
			<KEYWORD1>use</KEYWORD1>
			<KEYWORD1>library</KEYWORD1>
			<KEYWORD1>loop</KEYWORD1>
			<KEYWORD1>constant</KEYWORD1>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>port</KEYWORD1>
			<KEYWORD1>is</KEYWORD1>
			<KEYWORD1>of</KEYWORD1>
			<KEYWORD1>array</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>elsif</KEYWORD1>
			<KEYWORD1>when</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>downto</KEYWORD1>
			<KEYWORD1>upto</KEYWORD1>
			<KEYWORD1>extends</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>implements</KEYWORD1>
			<KEYWORD1>instanceof</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>static</KEYWORD1>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>type</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>others</KEYWORD1>
			<KEYWORD1>all</KEYWORD1>
			<KEYWORD1>record</KEYWORD1>
 			<KEYWORD1>range</KEYWORD1>
 			<KEYWORD1>wait</KEYWORD1>

			<KEYWORD2>package</KEYWORD2>
			<KEYWORD2>import</KEYWORD2>
			<KEYWORD2>std_logic</KEYWORD2>
			<KEYWORD2>std_ulogic</KEYWORD2>
			<KEYWORD2>std_logic_vector</KEYWORD2>
			<KEYWORD2>std_ulogic_vector</KEYWORD2>
			<KEYWORD2>integer</KEYWORD2>
			<KEYWORD2>natural</KEYWORD2>
			<KEYWORD2>bit</KEYWORD2>
			<KEYWORD2>bit_vector</KEYWORD2>
			

			<KEYWORD3>or</KEYWORD3>
			<KEYWORD3>nor</KEYWORD3>
			<KEYWORD3>not</KEYWORD3>
			<KEYWORD3>nand</KEYWORD3>
			<KEYWORD3>and</KEYWORD3>
			<KEYWORD3>xnor</KEYWORD3>
			<KEYWORD3>sll</KEYWORD3>
			<KEYWORD3>srl</KEYWORD3>
			<KEYWORD3>sla</KEYWORD3>
			<KEYWORD3>sra</KEYWORD3>
			<KEYWORD3>rol</KEYWORD3>
			<KEYWORD3>ror</KEYWORD3>
			<KEYWORD3>or</KEYWORD3>
			<KEYWORD3>or</KEYWORD3>
			<KEYWORD3>mod</KEYWORD3>
			<KEYWORD3>rem</KEYWORD3>
			<KEYWORD3>abs</KEYWORD3>

			<FUNCTION>rising_edge</FUNCTION>
			<FUNCTION>shift_left</FUNCTION>
			<FUNCTION>shift_right</FUNCTION>
			<FUNCTION>rotate_left</FUNCTION>
			<FUNCTION>rotate_right</FUNCTION>
			<FUNCTION>resize</FUNCTION>
			<FUNCTION>std_match</FUNCTION>
			<FUNCTION>to_integer</FUNCTION>
			<FUNCTION>to_unsigned</FUNCTION>
			<FUNCTION>to_signed</FUNCTION>
			<FUNCTION>unsigned</FUNCTION>
			<FUNCTION>signed</FUNCTION>
			<FUNCTION>to_bit</FUNCTION>
			<FUNCTION>to_bitvector</FUNCTION>
			<FUNCTION>to_stdulogic</FUNCTION>
			<FUNCTION>to_stdlogicvector</FUNCTION>
			<FUNCTION>to_stdulogicvector</FUNCTION>
			
			<LITERAL2>false</LITERAL2>
			<LITERAL2>true</LITERAL2>
		</KEYWORDS>
	</RULES>
</MODE>

=== linzhp/jEdit-Clone/modes/python.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Python mode, by Slava Pestov. Based on PythonTokenMarker by
  -- Jonathan Revusky -->
<MODE NAME="python">
	<PROPS>
		<PROPERTY NAME="label" VALUE="Python" />
		<PROPERTY NAME="blockComment" VALUE="#" />
		<PROPERTY NAME="filenameGlob" VALUE="*.py" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- Comment -->
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<!-- Triple-quotes -->
		<SPAN TYPE="LITERAL1">
			<BEGIN>"""</BEGIN>
			<END>"""</END>
		</SPAN>

		<SPAN TYPE="LITERAL1">
			<BEGIN>'''</BEGIN>
			<END>'''</END>
		</SPAN>

		<!-- Standard literals -->
		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="NULL">}</SEQ>
		<SEQ TYPE="NULL">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<SEQ TYPE="NULL">:</SEQ>

		<KEYWORDS IGNORE_CASE="FALSE">
			<KEYWORD3>and</KEYWORD3>
			<KEYWORD3>not</KEYWORD3>
			<KEYWORD3>or</KEYWORD3>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>assert</KEYWORD1>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>elif</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>except</KEYWORD1>
			<KEYWORD1>exec</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<KEYWORD1>raise</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD2>def</KEYWORD2>
			<KEYWORD2>class</KEYWORD2>
			<KEYWORD2>del</KEYWORD2>
			<KEYWORD2>from</KEYWORD2>
			<KEYWORD2>global</KEYWORD2>
			<KEYWORD2>import</KEYWORD2>
			<KEYWORD2>in</KEYWORD2>
			<KEYWORD2>is</KEYWORD2>
			<KEYWORD2>lambda</KEYWORD2>
			<KEYWORD2>pass</KEYWORD2>
			<KEYWORD2>print</KEYWORD2>
		</KEYWORDS>
	</RULES>
</MODE>

=== linzhp/jEdit-Clone/modes/macro.xml
<?XML VERSION="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE NAME="macro">
	<PROPS>
		<PROPERTY NAME="label" VALUE="jEdit Macro" />
		<PROPERTY NAME="filenameGlob" VALUE="*.macro" />
	</PROPS>
	<RULES>
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>
		<EOL_SPAN TYPE="COMMENT1" AT_LINE_START="TRUE">#</EOL_SPAN>
		<EOL_SPAN TYPE="LITERAL1">@</EOL_SPAN>
	</RULES>
</MODE>

=== linzhp/jEdit-Clone/modes/dsssl.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE NAME="dsssl">
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
		<PROPERTY NAME="boxComment" VALUE="--" />
		<PROPERTY NAME="blockComment" VALUE=";" />
		<PROPERTY NAME="filenameGlob" VALUE="*.{dsl,dsssl}" />
	</PROPS>
	<RULES IGNORE_CASE="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- DTD Entity declarations -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::ENTITY-TAGS">
			<BEGIN>&lt;!ENTITY</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- CDATA sections -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::CDATA">
			<BEGIN>&lt;![CDATA[</BEGIN>
			<END>]]&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- PI directives -->
		<SPAN TYPE="KEYWORD3">
			<BEGIN>&lt;?</BEGIN>
			<END>?&gt;</END>
		</SPAN>

		<!-- DSSSL code -->
		<SPAN TYPE="MARKUP" DELEGATE="lisp::MAIN">
			<BEGIN>&lt;STYLE-SPECIFICATION-BODY</BEGIN>
			<END>&lt;/STYLE-SPECIFICATION-BODY&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="xml::TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>
</MODE>
